#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : mpsoc.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Thu Sep 15 10:30:20 CST 2022
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved. 
#
# usage: mpsoc.sh [-help]
# usage: mpsoc.sh [-lib_map_path]
# usage: mpsoc.sh [-noclean_files]
# usage: mpsoc.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'mpsoc.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm axis_infrastructure_v1_1_0 axis_data_fifo_v2_0_3 xil_defaultlib xlconstant_v1_1_7 gtwizard_ultrascale_v1_7_8 cmac_usplus_v3_1_0 lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 axi_infrastructure_v1_1_0 axi_vip_v1_1_7 zynq_ultra_ps_e_vip_v1_0_7 qdma_v4_0_0)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "mpsoc.sh - Script generated by export_simulation (Vivado v2020.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/a4b7/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "/opt/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "/opt/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "/opt/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "/opt/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "/opt/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "/opt/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/a4b7/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "/opt/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/opt/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "/opt/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/opt/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axis_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/a4b7/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/8713/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_data_fifo_v2_0_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/a4b7/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/50d0/hdl/axis_data_fifo_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/a4b7/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_axis_data_fifo_0_0_1/sim/mpsoc_axis_data_fifo_0_0.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_axis_data_fifo_1_0_1/sim/mpsoc_axis_data_fifo_1_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/a4b7/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/fcfc/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/a4b7/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_cmac_const_0_0_1/sim/mpsoc_cmac_const_0_0.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_cmac_const_1_0_1/sim/mpsoc_cmac_const_1_0.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_cmac_const_gt_loopback_in_0_1/sim/mpsoc_cmac_const_gt_loopback_in_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work gtwizard_ultrascale_v1_7_8 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/a4b7/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/420f/hdl/gtwizard_ultrascale_v1_7_bit_sync.v" \
    "$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/420f/hdl/gtwizard_ultrascale_v1_7_gte4_drp_arb.v" \
    "$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/420f/hdl/gtwizard_ultrascale_v1_7_gthe4_delay_powergood.v" \
    "$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/420f/hdl/gtwizard_ultrascale_v1_7_gtye4_delay_powergood.v" \
    "$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/420f/hdl/gtwizard_ultrascale_v1_7_gthe3_cpll_cal.v" \
    "$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/420f/hdl/gtwizard_ultrascale_v1_7_gthe3_cal_freqcnt.v" \
    "$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/420f/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal.v" \
    "$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/420f/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_rx.v" \
    "$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/420f/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_tx.v" \
    "$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/420f/hdl/gtwizard_ultrascale_v1_7_gthe4_cal_freqcnt.v" \
    "$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/420f/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal.v" \
    "$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/420f/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_rx.v" \
    "$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/420f/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_tx.v" \
    "$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/420f/hdl/gtwizard_ultrascale_v1_7_gtye4_cal_freqcnt.v" \
    "$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/420f/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_rx.v" \
    "$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/420f/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_tx.v" \
    "$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/420f/hdl/gtwizard_ultrascale_v1_7_gtwiz_reset.v" \
    "$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/420f/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_rx.v" \
    "$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/420f/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_tx.v" \
    "$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/420f/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_rx.v" \
    "$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/420f/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_tx.v" \
    "$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/420f/hdl/gtwizard_ultrascale_v1_7_reset_sync.v" \
    "$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/420f/hdl/gtwizard_ultrascale_v1_7_reset_inv_sync.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/a4b7/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_cmac_usplus_0_0_1/ip_0/sim/gtwizard_ultrascale_v1_7_gtye4_channel.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_cmac_usplus_0_0_1/ip_0/sim/mpsoc_cmac_usplus_0_0_gt_gtye4_channel_wrapper.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_cmac_usplus_0_0_1/ip_0/sim/gtwizard_ultrascale_v1_7_gtye4_common.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_cmac_usplus_0_0_1/ip_0/sim/mpsoc_cmac_usplus_0_0_gt_gtye4_common_wrapper.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_cmac_usplus_0_0_1/ip_0/sim/mpsoc_cmac_usplus_0_0_gt_gtwizard_gtye4.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_cmac_usplus_0_0_1/ip_0/sim/mpsoc_cmac_usplus_0_0_gt_gtwizard_top.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_cmac_usplus_0_0_1/ip_0/sim/mpsoc_cmac_usplus_0_0_gt.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_cmac_usplus_0_0_1/cmac_usplus_v3_1_0/mpsoc_cmac_usplus_0_0_wrapper.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_cmac_usplus_0_0_1/cmac_usplus_v3_1_0/mpsoc_cmac_usplus_0_0_ultrascale_tx_userclk.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_cmac_usplus_0_0_1/cmac_usplus_v3_1_0/mpsoc_cmac_usplus_0_0_ultrascale_rx_userclk.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work cmac_usplus_v3_1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/a4b7/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/35be/hdl/cmac_usplus_v3_1_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/a4b7/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_cmac_usplus_0_0_1/mpsoc_cmac_usplus_0_0/example_design/mpsoc_cmac_usplus_0_0_axis2lbus_segmented_top.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_cmac_usplus_0_0_1/mpsoc_cmac_usplus_0_0/example_design/mpsoc_cmac_usplus_0_0_lbus2axis_segmented_top.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_cmac_usplus_0_0_1/mpsoc_cmac_usplus_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_pl_clk_sys_reset_0_1/sim/mpsoc_pl_clk_sys_reset_0.vhd" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_rx_reset_0_1/sim/mpsoc_rx_reset_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/a4b7/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/mpsoc/ipshared/cc40/rx_reset_cnt.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_rx_reset_cnt_0_0_1/sim/mpsoc_rx_reset_cnt_0_0.v" \
    "$ref_dir/../../../bd/mpsoc/ipshared/07af/padding.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_tx_padding_0_0_1/sim/mpsoc_tx_padding_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_tx_reset_0_1/sim/mpsoc_tx_reset_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/a4b7/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_7 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/a4b7/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/ce6c/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work zynq_ultra_ps_e_vip_v1_0_7 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/a4b7/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/e257/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/a4b7/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_zynq_mpsoc_0_1/sim/mpsoc_zynq_mpsoc_0_vip_wrapper.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/ip_0/sim/gtwizard_ultrascale_v1_7_gthe4_channel.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/ip_0/sim/mpsoc_qdma_0_0_pcie4_ip_gt_gthe4_channel_wrapper.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/ip_0/sim/gtwizard_ultrascale_v1_7_gthe4_common.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/ip_0/sim/mpsoc_qdma_0_0_pcie4_ip_gt_gthe4_common_wrapper.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/ip_0/sim/mpsoc_qdma_0_0_pcie4_ip_gt_gtwizard_gthe4.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/ip_0/sim/mpsoc_qdma_0_0_pcie4_ip_gt_gtwizard_top.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/ip_0/sim/mpsoc_qdma_0_0_pcie4_ip_gt.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_gtwizard_top.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_phy_ff_chain.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_phy_pipeline.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_512b_async_fifo.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_512b_cc_intfc.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_512b_cc_output_mux.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_512b_cq_intfc.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_512b_cq_output_mux.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_512b_intfc_int.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_512b_intfc.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_512b_rc_intfc.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_512b_rc_output_mux.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_512b_rq_intfc.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_512b_rq_output_mux.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_512b_sync_fifo.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_bram_16k_int.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_bram_16k.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_bram_32k.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_bram_4k_int.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_bram_msix.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_bram_rep_int.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_bram_rep.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_bram_tph.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_bram.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_gt_gt_channel.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_gt_gt_common.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_gt_phy_clk.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_gt_phy_rst.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_gt_phy_rxeq.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_gt_phy_txeq.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_sync_cell.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_sync.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_gt_cdr_ctrl_on_eidle.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_gt_receiver_detect_rxterm.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_gt_phy_wrapper.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_init_ctrl.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_pl_eq.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_vf_decode.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_pipe.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_phy_top.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_seqnum_fifo.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_sys_clk_gen_ps.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source/mpsoc_qdma_0_0_pcie4_ip_pcie4_uscale_core_top.v" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/sim/mpsoc_qdma_0_0_pcie4_ip.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work qdma_v4_0_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/a4b7/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/a4b7/hdl/qdma_v4_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/a4b7/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/mpsoc_qdma_0_0hdl/verilog/mpsoc_qdma_0_0_core_top.sv" \
    "$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/sim/mpsoc_qdma_0_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/a4b7/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/mpsoc/ip/mpsoc_system_ila_0_0/bd_0/sim/bd_3194.v" \
    "$ref_dir/../../../bd/mpsoc/ip/mpsoc_system_ila_0_0/bd_0/ip/ip_0/sim/bd_3194_ila_lib_0.v" \
    "$ref_dir/../../../bd/mpsoc/ip/mpsoc_system_ila_0_0/sim/mpsoc_system_ila_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/mpsoc/ip/mpsoc_rx_datapath_reset_0/sim/mpsoc_rx_datapath_reset_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/e257/hdl" +incdir+"$ref_dir/../../../../doce_nf.gen/sources_1/bd/mpsoc/ip/mpsoc_qdma_0_0_1/ip_0/source" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/a4b7/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../doce_nf.srcs/sources_1/bd/mpsoc/ipshared/c968/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/mpsoc/ip/mpsoc_xlconstant_0_0/sim/mpsoc_xlconstant_0_0.v" \
    "$ref_dir/../../../bd/mpsoc/sim/mpsoc.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.mpsoc xil_defaultlib.glbl -o mpsoc_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./mpsoc_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./mpsoc.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/huangtianyi/doce_nf_work_axist/doce_nf.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key mpsoc_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc mpsoc_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./mpsoc.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: mpsoc.sh [-help]\n\
Usage: mpsoc.sh [-lib_map_path]\n\
Usage: mpsoc.sh [-reset_run]\n\
Usage: mpsoc.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
