# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/BufferFifoIP_512/BufferFifoIP_512.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BufferFifoIP_512 || ORIG_REF_NAME==BufferFifoIP_512} -quiet] -quiet
