# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Chisel/chisel_dev/smart_nic_sim/smart_nic.srcs/sources_1/ip/BufferFifoIP_512/BufferFifoIP_512.xci
# IP: The module: 'BufferFifoIP_512' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Chisel/chisel_dev/smart_nic_sim/smart_nic.srcs/sources_1/ip/BufferFifoIP_512/BufferFifoIP_512_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BufferFifoIP_512'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/Chisel/chisel_dev/smart_nic_sim/smart_nic.srcs/sources_1/ip/BufferFifoIP_512/BufferFifoIP_512.xci
# IP: The module: 'BufferFifoIP_512' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Chisel/chisel_dev/smart_nic_sim/smart_nic.srcs/sources_1/ip/BufferFifoIP_512/BufferFifoIP_512_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BufferFifoIP_512'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
